Geeks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('last.urls')),
    path('accounts/',include("django.contrib.auth.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

last/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from last import views

app_name = "last"

urlpatterns = [
    path('', views.index, name="index"),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('all_projects/', views.all_projects, name='all_projects'),
    path('all_hackathons/', views.all_hackathons, name='all_hackathons'),
    path('hackathon/<int:hackathon_id>', views.hackathon_detail, name='hackathon_details'),
    path('profile/<str:pk>/', views.UserProfile, name="profile"),
    path('members/', views.members, name="members"),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('edit-profile/', views.updateProfile, name="edit-profile"),
    path('update_hackathon/<int:hackathon_id>/', views.updateHackathon, name='update-hackathon'),
    path('edit_contact/<int:contact_id>/', views.edit_contact, name='edit-contact'),
    path('edit_project/<int:project_id>/', views.edit_project, name='edit-project'),
    path('add_hackathon/', views.add_hackathon, name='add-hackathon'),
    path('add_project/', views.add_project, name='add-project'),
    path('project/<int:project_id>/', views.edit_project, name='project_detail'),
    path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('hackathon/<int:hackathon_id>/delete/', views.delete_hackathon, name='delete_hackathon'),
    path('profile/<int:user_id>/delete/', views.delete_profile, name='delete_profile'),
    path('add-contact/', views.add_contact, name='add_contact'),
    path('edit-contact/<int:contact_id>/', views.edit_contact, name='edit_contact'),
    path('delete-contact/<int:contact_id>/', views.delete_contact, name='delete_contact'),
    path('join-hackathon/<int:hackathon_id>/', views.join_hackathon, name='join_hackathon'),
    path('grade-participant/<int:hackathon_id>/<int:participant_id>/', views.grade_participant,
         name='grade_participant'),

    path('hackathon/<int:hackathon_id>/download-report/', views.download_hackathon_report,
                       name='download_hackathon_report'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'last.views.error_404_view'

handler403 = 'last.views.error_403_view'

handler401 = 'last.views.error_401_view'

handler400 = 'last.views.error_400_view'

handler500 = 'last.views.error_500_view'

templates/401.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static '/css/error.css' %}">
  <title>Your Page Title</title>
</head>
<body>

<section class="content">
  <section class="loader_section" id="loaderSection">
    <div class="loader">
      <div style="--i: 1"></div>
      <div style="--i: 2"></div>
      <div style="--i: 3"></div>
      <div style="--i: 4"></div>
    </div>
    <img src="{% static 'img/imageload.png' %}" alt="">
  </section>
  <section class="wrap-error">
  <div>
    <div class="d-flex align-items-center h-100">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 offset-sm-2 text-center text-white">
            <h1 class=""><span>4</span><span>0</span><span>1</span></h1>
            <h5 class="">Oops! Unauthorized</h5>
            <p class="mb-4">we are sorry, but the page you requested needs authentication credentials</p>
            <a class="btn btn-dark" href="/" title="home url">
              Go home
              </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  </section>
  </section>

</body>
</html>

templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <!-- Add your other CSS or head elements here -->
</head>
<body>

<div class="container-fluid">
 <header class="  p-4">
            <h1>Geeks Dashboard</h1>

            <!-- Mobile menu toggle button -->
            <button class="menu__toggle">&#9776;</button>

            <!-- Navigation menu -->
            <ul class="header__menu">
                <li class="menu__item">
                    <a href="{% url 'last:index' %}" class="menu__link active">Home</a>
                </li>
                <li class="menu__item">
                    <a href="{% url 'last:all_projects' %}" class="menu__link">Projects</a>
                </li>
                <li class="menu__item">
                    <a href="{% url 'last:members' %}" class="menu__link">Members</a>
                </li>
                <li class="menu__item">
                    <a href="{% url 'last:all_hackathons' %}" class="menu__link">Hackathons</a>
                </li>
                <li class="menu__item">
                    <a href="{% url 'last:index' %}" class="menu__link">Contact</a>
                </li>
             <li class="menu__item">
                            <a href="{% url 'last:dashboard' %}" class="menu__link">Dashboard</a>
                        </li>
                {% if request.user.is_authenticated %}
                <li class="menu__item">
                    <a href="{% url 'last:profile' user.id %}">Profile</a>
                </li>
                {% endif %}
                <li class="menu__item">
                    <!-- Uncomment this line if you want a separate link for 'Hackathons' -->
{#                    <!-- <a href="{% url 'last:hackathons' %}" class="menu__link">Hackathons</a> -->#}
                </li>
            </ul>
 </header>

<div  class="content">
    <section class="logo_image">
        <img src="{% static 'img/dashboardlogo.png' %}" alt="">
    </section>
   <!-- Search Bar -->
 <!-- Search Section -->
    <section class="search-section mt-4">
{#        <h2>Search</h2>#}
        <form id="searchForm" method="get" action="{% url 'last:dashboard' %}">
            <input type="text" name="search" id="searchInput" placeholder="Search...">
            <button type="submit">Search</button>
        </form>
    </section>

    <section class="stats-section mt-4">
        <div class="row startsrow">
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Total Users</h5>
                        <p class="card-text">{{ user_count }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Project Count</h5>
                        <p class="card-text">{{ project_count }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Hackathon Count</h5>
                        <p class="card-text">{{ hackathon_count }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Active Users (last 30 days)</h5>
                        <p class="card-text">{{ active_user_count }}</p>
                    </div>
                </div>
            </div>

        </div>
        <!-- Color Scheme Explanation -->
       <div class="color-scheme-section mt-4">
            <h2>Color Scheme Explanation</h2>
            <ul>
                <li><span class="badge badge-light">0 Projects</span> White</li>
                <li><span class="badge badge-danger">1-2 Projects</span> Red</li>
                <li><span class="badge badge-primary">4-5 Projects</span> Blue</li>
                <!-- Add more levels as needed -->
            </ul>
        </div>
    </section>

    <section class="recent-projects-section mt-4">
         <h2>Recent Projects</h2>
            <div class="row row_project_card">
                {% for project in recent_projects %}
                    <div class="col-md-4 {% if project.title == highlight_project %}highlight{% endif %}">
                        <div class="card project_card">
                            <img src="{{ project.image.url }}" class="card-img-top" alt="{{ project.title }} Image">
                            <div class="card-body project_card_text">
                                <h5 class="card-title color">{{ project.title }}</h5>
                                <p class="card-text color">{{ project.description }}</p>
                                <p class="card-text "><small class="text-muted color">Created {{ project.time_since_created }}</small></p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
    </section>

    <section class="upcoming-hackathons-section mt-4">
        <h2>Upcoming Hackathons</h2>
            <div class="row">
                {% for hackathon in upcoming_hackathons %}
                    <div class="col-md-4 {% if hackathon.name == highlight_hackathon %}highlight{% endif %} ">
                        <div class="card project_card">
                            <img src="{{ hackathon.image.url }}" class="card-img-top" alt="{{ hackathon.name }} Image">
                            <div class="card-body project_card_text">
                                <h5 class="card-title">{{ hackathon.name }}</h5>
                                <p class="card-text">{{ hackathon.theme }}</p>
                                <p class="card-text"><small class="text-muted">Starts {{ hackathon.time_until_start }}</small></p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
    </section>

   <section class="recent-activities-section mt-4">
    <h2>Recent Activities</h2>
    <div class="activity-list">
        <ul class="list-group">
            {% for activity in recent_activities %}
                <li class="list-group-item">
                    <div class="activity-item">
                        <div class="activity-category color">{{ activity.category }}</div>
                        <div class="activity-details color">
                            <div class="activity-title color">{{ activity.title }}</div>
                            <div class="activity-time color">{{ activity.time_since }} </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
</section>

<!-- New User Section -->
<section class="user-section mt-4" id="user-section">
    <h2>Users</h2>
    <div class="user-list-container">
        <ul class="user-list">
            {% for user in users %}
                <li class="user-item {% if user.username == highlight_user %}highlight{% endif %}">
                    <!-- Add 'highlight' class if it matches the search result -->
                    <div class="card">
                        <img src="{{ user.avatar.url }}" class="card-img-top users_avatar" alt="{{ user.username }} Avatar">
                        <div class="card-body  users_cardbody">
                            <h5 class="card-title bold"> <a href="{% url 'last:profile' user.id %}">{{ user.username }}</a></h5>
                            <p class="card-text bold">{{ user.tag }}</p>
                            <p class="card-text bold">Project Count: {{ user.projects.count }}</p>
                            <p class="card-text bold">Hackathon Count: {{ user.hackathon_founder.count }}</p>
                            <p class="card-text bold">Date Joined: {{ user.joined|date }}</p>
                            <!-- Add more user information as needed -->
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
</section>
<!-- Highlighted Project Section -->
<section class="highlighted-project-section mt-4" id="highlighted-project-section">
    {% if highlight_project %}
        <h2>Highlighted Project</h2>
        <!-- Add the content for the highlighted project -->
    {% endif %}
</section>

<!-- Highlighted Hackathon Section -->
<section class="highlighted-hackathon-section mt-4" id="highlighted-hackathon-section">
    {% if highlight_hackathon %}
        <h2>Highlighted Hackathon</h2>
        <!-- Add the content for the highlighted hackathon -->
    {% endif %}
</section>

    <!-- Graph Section -->
    <section class="graph-section mt-4">
        <h2>Graph Section</h2>
        <!-- Bar chart canvas -->
        <canvas id="projectCountChart" width="400" height="200"></canvas>
        <script>
            // Data for the chart
            var userData = JSON.parse('{{ user_data_json|escapejs }}');
            var labels = userData.map(function(user) { return user.username; });
            var projectCounts = userData.map(function(user) { return user.projects_count; });

            // Create a bar chart
            var ctx = document.getElementById('projectCountChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: labels,
                    datasets: [{
                        label: 'Project Count',
                        data: projectCounts,
                        backgroundColor: 'rgba(75, 192, 192, 0.2)',
                        borderColor: 'rgba(75, 192, 192, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });
        </script>
    </section>
<!-- End Graph Section -->
    <!-- Add more sections or content as needed -->
</div>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        // Check if there's an anchor in the URL
        var urlParams = new URLSearchParams(window.location.search);
        var anchor = urlParams.get("anchor");

        if (anchor) {
            // Scroll to the element with the specified ID
            var element = document.getElementById(anchor);
            if (element) {
                element.scrollIntoView({ behavior: "smooth" });
            }
        }
    });
</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="{% static 'js/dashboard.js' %}"></script>
<script src="{% static 'js/mobile.js' %}"></script>
<!-- Add your other scripts or body elements here -->

</body>
</html>

templates/user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, 
    initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Zou Farm</title>
    <link rel="icon" type="image/png" href="{% static 'img/logo.svg'%}">
    <link rel="stylesheet" href="{% static '/css/members.css'%}">
    <link rel="stylesheet" href="{% static  '/css/user.css'%}">
    <link  rel="stylesheet" 
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" 
    integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" 
    crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="{% static '/css/main.css'%}">
</head>

<body>
    <div class="container">
        <header>
            <nav class="header__nav w-120">
                <div class="header__logo">
                   <a href="/"> <img src="{% static '/img/logo2.png' %}" alt="Logo"></a>
                </div>
                <div class="header__nav__content">
                    <div class="nav-close-icon"></div>
                    <ul class="header__menu">
                        <li class="menu__item">
                            <a href="#" class="menu__link active">Home</a>
                        </li>
                        <li class="menu__item">
                            <a href="#" class="menu__link">About</a>
                        </li>
                        <li class="menu__item">
                            <a href="#" class="menu__link">Projects</a>
                        </li>
                        <li class="menu__item">
                            <a href="#" class="menu__link">Team</a>
                        </li>
                        <li class="menu__item">
                            <a href="#" class="menu__link">Contact</a>
                        </li>
                         <li class="menu__item">
                            <a href="{% url 'last:dashboard' %}" class="menu__link">Dashboard</a>
                        </li>
                    </ul>
                    <div class="header__signup">
                        <a href="#" class="btn btn__signup">
                            <i class="fas fa-user-plus"></i> Sign Up
                        </a>
                    </div>
                </div>

                <div class="hamburger-menu-wrap">
                    <div class="hamburger-menu">
                        <div class="line"></div>
                        <div class="line"></div>
                        <div class="line"></div>
                        <div class="line"></div>
                    </div>
                </div>
            </nav>
        </header>
        <section class="member__user">
            <div class="member__user__content">
                <div class="member__user__body">
                    <div class="member__user__list">
                        <div class="userr">
                            <div class="user__profile">
                                <div class="user__img">
                                    <img src="{% static '/img/testimonials/test.png'%}" alt="Testimonial">
                                </div>
                                <div class="user__info">
                                    <h4 class="user__name"> Bico Steve </h4>
                                    <h4 class="user__title">Backend Developer </h4>
                                </div>
                                <div class="edit">
                                    <i class="fa-solid fa-pen"></i>
                                    <i class="fa-regular fa-trash-can"></i>
                                </div>
                            </div>
                            <p class="user__description">
                                A third year computer science student who is passionate about 
                                computing, and enjoys learning new staff.
                            </p>
                            <div class="edit">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="socials">
            <div class="socials__img">
                <img src="{% static '/img/laptop2.png' %}" alt="">
            </div>
            <div class="socials__content w-105">
                <div class="socials__head">
                    <h2 class="socials__title">Connect with Me</h2>
                    <p class="socials__description">
                        Below are some of my accounts lets connect.
                    </p>
                </div>
                <div class="socials__body">
                    <div class="social">
                        <img src="{% static '/img/opportunites/opportunity-1.svg'%}" 
                        alt="github" class="social__icon">
                        <h4 class="social__title"><a href="">GitHub</a></h4>
                    </div>

                    <div class="social active">
                        <img src="{% static '/img/opportunites/opportunity-2.svg'%}" alt="Icon" class="opportunity__icon">
                        <h4 class="social__title">Instagram</h4>
                    </div>
                    <div class="social">
                        <img src="{% static '/img/opportunites/opportunity-3.svg'%}" alt="Icon" class="opportunity__icon">
                        <h4 class="social__title">Twitter
                        </h4>
                    </div>
                    <div class="social active">
                        <img src="{% static '/img/opportunites/opportunity-2.svg'%}" alt="Icon" class="opportunity__icon">
                        <h4 class="social__title">Dev</h4>
                    </div>
                    <div class="social">
                        <img src="{% static '/img/opportunites/opportunity-3.svg'%}" alt="Icon" class="opportunity__icon">
                        <h4 class="social__title">HackerRank
                        </h4>
                    </div>
                    <div class="social active">
                        <img src="{% static '/img/opportunites/opportunity-2.svg'%}" alt="Icon" class="opportunity__icon">
                        <h4 class="social__title">Dev</h4>
                    </div>
                </div>
            </div>
        </section>

        <section class="invest  w-105">
            <div class="invest__content">
                <div class="invest__head">
                    <h2 class="invest__title">Some of Steve's Projects and Hackathons</h2>
                    <p class="invest__description">Below are some of the collaborative 
                        projects that the team members have done some are hosted live 
                        while others are not. Because of the costa of hosting projects 
                        come with but check them out and you can contact us for any info 
                        on what we should improve or have done better.  </p>
                </div>
                <div class="invest__body">
                    <div class="invest__item">
                        <div class="invest__item__head">
                            <h5 class="invest__item__subtitle">1st Jan-2023</h5>
                        </div>
                        <div class="invest__item__body">
                            <h4 class="invest__item__title">Reserve Room</h4>
                            <p class="invest__item_description">
                                The Website allows you to reserve a hotel room prior 
                                to your travel.Saving you of the hustle.
                            </p>
                        </div>
                        <div class="invest__item__footer">
                            <a href="#" class="btn btn__invest">Check It Out</a>
                        </div>
                    </div>
                    <div class="invest__item">
                        <div class="invest__item__head">
                            <h5 class="invest__item__subtitle">3rd Feb-2023</h5>
                        </div>
                        <div class="invest__item__body">
                            <h4 class="invest__item__title">Study Manager
                            </h4>
                            <p class="invest__item_description">
                                The website is meant to make learning easy and fun, 
                                helping you manage your progress.It's also meant to 
                                keep students on track.
                            </p>
                        </div>
                        <div class="invest__item__footer">
                            <a href="#" class="btn btn__invest">Check It Out</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="farm-invest w-105">
            <h2 class="farm-invest__title">Be Sure to Join <span>Geeks Team</span> so that We can Learn and Practice Together.</h2>
            <a href="#" class="btn btn__farm--invest">Sign up Now</a>

        </section>

        <footer class="footer">
            <div class="footer__body w-105">
                <nav class="footer__nav">
                    <ul class="footer_nav__menu">
                        <li class="footer_nav__item">
                            <h4 class="footer_nav__menu__title">COMPANY</h4>
                        </li>
                        <li class="footer_nav__item">
                            <a href="#" class="footer_nav__link">About Us</a>
                        </li>
                        <li class="footer_nav__item">
                            <a href="#" class="footer_nav__link">Team</a>
                        </li>
                        <li class="footer_nav__item">
                            <a href="#" class="footer_nav__link">Careers</a>
                        </li>
                        <li class="footer_nav__item">
                            <a href="#" class="footer_nav__link">Contact</a>
                        </li>
                    </ul>
                    <ul class="footer_nav__menu">
                        <li class="footer_nav__item">
                            <h4 class="footer_nav__menu__title">INVEST</h4>
                        </li>
                        <li class="footer_nav__item">
                            <a href="#" class="footer_nav__link">Features</a>
                        </li>
                        <li class="footer_nav__item">
                            <a href="#" class="footer_nav__link">How it works</a>
                        </li>
                        <li class="footer_nav__item">
                            <a href="#" class="footer_nav__link">Pricing</a>
                        </li>
                        <li class="footer_nav__item">
                            <a href="#" class="footer_nav__link">Login</a>
                        </li>
                    </ul>
                    <ul class="footer_nav__menu">
                        <li class="footer_nav__item">
                            <h4 class="footer_nav__menu__title">LEGAL</h4>
                        </li>
                        <li class="footer_nav__item">
                            <a href="#" class="footer_nav__link">Privacy</a>
                        </li>
                        <li class="footer_nav__item">
                            <a href="#" class="footer_nav__link">Terms</a>
                        </li>
                        <li class="footer_nav__item">
                            <a href="#" class="footer_nav__link">Security</a>
                        </li>
                    </ul>
                </nav>
                <div class="footer__contact">
                    <h5 class="footer__contact__title">Geeks Team</h5>
                    <span>Write email to us</span>
                    <form action="">
                        <input type="text" name="name" placeholder="Enter Name">
                        <input type="email" name="email" placeholder="Enter Email">
                        <textarea name="message" id="" cols="30" rows="10" placeholder="Enter Message"></textarea>
                        <a href="#" class="btn btn__signin">
                            <i class="fas fa-paper-plane"></i> Send
                        </a>
                    </form>   
                <small>Phone: 0757838398</small>
                </div>
            </div>
            <div class="footer__bottom">
                <div class="footer__bottom__content w-105">
                    <div class="footer__logo">
                        <img src="{% static '/img/logo.png'%}" alt="Logo">
                    </div>
                    <p class="footer_copyright">
                        © Copyright 2023. Geeks By Steve Rebrand.
                    </p>
                </div>
                <img src="{% static '/img/down.png'%}" alt="Down" class="footer_img">
            </div>
        </footer>
    </div>
    <script src="{% static '/js/main.js' %}" type="module"></script>

</body>

</html>